### ISSUE TITLE
Wrong OpenTree link

### ISSUE THREAD

**Issue by snacktavish** [biotaphy/analyses#67]
Hi - not sure this is the right place to put this, but I didn't find any contact links on the Biotaphy platform (http://client.lifemapper.org/biotaphy/)

The OpenTree links on the Biotaphy platform point to an OpenTree development server
(https://ot38.opentreeoflife.org) rather than the production server (tree.opentreeoflife.org). This is likely to lead to some unexpected and/or unreliable behavior, especially if API calls are also going there.

**Comment by cjgrady** [comment]
Thanks for the heads up about the missing link on that page.  You can find our contact info in the future at: http://lifemapper.org/?page_id=62.  I'll see if we can make that easier to get to though.

As for the Open Tree links, we had to link to a development server because we needed a version that produced branch lengths from the induce subtree operation.  I would be more than happy to switch to the production instance if that functionality is now in place.

We actually have another repository for our OpenTree wrapper, https://github.com/biotaphy/ot_service_wrapper, could you open an issue there?  Also, do you manage the production server or can you at least help us with the service call?

**Comment by snacktavish** [comment]
Moved discussion to https://github.com/biotaphy/ot_service_wrapper/issues/1
